-- Enable vector extension (install pgvector first if needed)
CREATE EXTENSION IF NOT EXISTS vector;

-- Custom types
CREATE TYPE "chat_mode" AS ENUM (
  'learning',
  'evaluation'
);

CREATE TYPE "chat_channel" AS ENUM (
  'text',
  'voice',
  'mixed'
);

CREATE TYPE "message_role" AS ENUM (
  'user',
  'assistant',
  'system'
);

CREATE TYPE "message_modality" AS ENUM (
  'text',
  'voice'
);

CREATE TYPE "grade_level" AS ENUM (
  '6 - 8',
  '9 - 11',
  '12 - 13',
  'university'
);

CREATE TYPE "resource_source" AS ENUM (
  'user_upload',
  'url',
  'system'
);

CREATE TYPE "resource_role" AS ENUM (
  'syllabus',
  'question_paper',
  'answer_script'
);

CREATE TYPE "evaluation_status" AS ENUM (
  'pending',
  'processing',
  'completed',
  'failed'
);

-- Tables
CREATE TABLE "users" (
  "id" uuid PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "full_name" varchar,
  "password_hash" varchar NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_login_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "chat_sessions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "mode" chat_mode NOT NULL DEFAULT 'learning',
  "channel" chat_channel NOT NULL DEFAULT 'text',
  "title" varchar,
  "description" text,
  "grade" int,
  "subject" varchar,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "resource_files" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "original_filename" varchar,
  "storage_path" varchar,
  "mime_type" varchar,
  "size_bytes" bigint,
  "source_type" resource_source,
  "language" varchar,
  "created_at" timestamptz
);

CREATE TABLE "session_resources" (
  "session_id" uuid NOT NULL,
  "resource_id" uuid NOT NULL,
  "label" varchar,
  PRIMARY KEY ("session_id", "resource_id")
);

CREATE TABLE "messages" (
  "id" uuid PRIMARY KEY,
  "session_id" uuid NOT NULL,
  "role" message_role,
  "modality" message_modality,
  "content" text,
  "grade_level" grade_level,
  "audio_url" varchar,
  "transcript" text,
  "audio_duration_sec" numeric,
  "model_name" varchar,
  "prompt_tokens" int,
  "completion_tokens" int,
  "total_tokens" int,
  "created_at" timestamptz
);

CREATE TABLE "message_attachments" (
  "id" uuid PRIMARY KEY,
  "message_id" uuid NOT NULL,
  "resource_id" uuid NOT NULL,
  "display_name" varchar,
  "attachment_type" varchar,
  "created_at" timestamptz
);

CREATE TABLE "message_safety_reports" (
  "id" uuid PRIMARY KEY,
  "message_id" uuid NOT NULL,
  "missing_concepts" jsonb,
  "extra_concepts" jsonb,
  "flagged_sentences" jsonb,
  "reasoning" jsonb,
  "created_at" timestamptz
);

CREATE TABLE "resource_chunks" (
  "id" uuid PRIMARY KEY,
  "resource_id" uuid NOT NULL,
  "chunk_index" int,
  "content" text,
  "content_length" int,
  "token_count" int,
  "embedding" vector(768),
  "embedding_model" varchar,
  "start_char" int,
  "end_char" int
);

CREATE TABLE "message_context_chunks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_id" uuid NOT NULL,
  "chunk_id" uuid NOT NULL,
  "similarity_score" numeric,
  "rank" int
);

CREATE TABLE "refresh_tokens" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL,
  "token_jti" varchar NOT NULL UNIQUE,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "created_at" timestamptz DEFAULT now()
);

CREATE TABLE "password_reset_tokens" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL,
  "token_jti" varchar NOT NULL UNIQUE,
  "expires_at" timestamptz NOT NULL,
  "used_at" timestamptz,
  "revoked_at" timestamptz,
  "created_at" timestamptz DEFAULT now()
);

CREATE TABLE "evaluation_sessions" (
  "id" uuid PRIMARY KEY,
  "session_id" uuid NOT NULL,
  "rubric_id" uuid,
  "status" evaluation_status,
  "created_at" timestamptz
);

CREATE TABLE "evaluation_resources" (
  "id" uuid PRIMARY KEY,
  "evaluation_session_id" uuid NOT NULL,
  "resource_id" uuid NOT NULL,
  "role" resource_role
);

CREATE TABLE "paper_config" (
  "id" uuid PRIMARY KEY,
  "evaluation_session_id" uuid NOT NULL,
  "paper_part" varchar,
  "subject_name" varchar,
  "medium" varchar,
  "weightage" numeric(5,2),
  "total_main_questions" int,
  "selection_rules" jsonb,
  "is_confirmed" boolean DEFAULT false,
  "created_at" timestamptz
);

CREATE TABLE "question_papers" (
  "id" uuid PRIMARY KEY,
  "evaluation_session_id" uuid NOT NULL,
  "resource_id" uuid NOT NULL,
  "extracted_text" text,
  "created_at" timestamptz
);

CREATE TABLE "questions" (
  "id" uuid PRIMARY KEY,
  "question_paper_id" uuid NOT NULL,
  "question_number" varchar,
  "question_text" text,
  "max_marks" int
);

CREATE TABLE "sub_questions" (
  "id" uuid PRIMARY KEY,
  "question_id" uuid NOT NULL,
  "label" varchar,
  "sub_question_text" text,
  "max_marks" int
);

CREATE TABLE "rubrics" (
  "id" uuid PRIMARY KEY,
  "name" varchar,
  "description" text,
  "rubric_type" varchar,
  "created_by" uuid,
  "created_at" timestamptz
);

CREATE TABLE "rubric_criteria" (
  "id" uuid PRIMARY KEY,
  "rubric_id" uuid NOT NULL,
  "criterion" varchar,
  "weight_percentage" int,
  "created_at" timestamptz
);

CREATE TABLE "answer_documents" (
  "id" uuid PRIMARY KEY,
  "evaluation_session_id" uuid NOT NULL,
  "resource_id" uuid NOT NULL,
  "student_identifier" varchar,
  "created_at" timestamptz
);

CREATE TABLE "evaluation_results" (
  "id" uuid PRIMARY KEY,
  "answer_document_id" uuid NOT NULL,
  "total_score" numeric,
  "overall_feedback" text,
  "evaluated_at" timestamptz
);

CREATE TABLE "question_scores" (
  "id" uuid PRIMARY KEY,
  "evaluation_result_id" uuid NOT NULL,
  "sub_question_id" uuid NOT NULL,
  "awarded_marks" numeric,
  "feedback" text
);

-- Foreign keys
ALTER TABLE "chat_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "resource_files" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "session_resources" ADD FOREIGN KEY ("session_id") REFERENCES "chat_sessions" ("id");

ALTER TABLE "session_resources" ADD FOREIGN KEY ("resource_id") REFERENCES "resource_files" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("session_id") REFERENCES "chat_sessions" ("id");

ALTER TABLE "resource_chunks" ADD FOREIGN KEY ("resource_id") REFERENCES "resource_files" ("id");

ALTER TABLE "message_context_chunks" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id");

ALTER TABLE "message_context_chunks" ADD FOREIGN KEY ("chunk_id") REFERENCES "resource_chunks" ("id");

ALTER TABLE "message_attachments" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id");

ALTER TABLE "message_attachments" ADD FOREIGN KEY ("resource_id") REFERENCES "resource_files" ("id");

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "password_reset_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "evaluation_sessions" ADD FOREIGN KEY ("session_id") REFERENCES "chat_sessions" ("id");

ALTER TABLE "evaluation_resources" ADD FOREIGN KEY ("evaluation_session_id") REFERENCES "evaluation_sessions" ("id");

ALTER TABLE "evaluation_resources" ADD FOREIGN KEY ("resource_id") REFERENCES "resource_files" ("id");

ALTER TABLE "paper_config" ADD FOREIGN KEY ("evaluation_session_id") REFERENCES "evaluation_sessions" ("id");

ALTER TABLE "question_papers" ADD FOREIGN KEY ("evaluation_session_id") REFERENCES "evaluation_sessions" ("id");

ALTER TABLE "questions" ADD FOREIGN KEY ("question_paper_id") REFERENCES "question_papers" ("id");

ALTER TABLE "sub_questions" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id");

ALTER TABLE "rubric_criteria" ADD FOREIGN KEY ("rubric_id") REFERENCES "rubrics" ("id");

ALTER TABLE "answer_documents" ADD FOREIGN KEY ("evaluation_session_id") REFERENCES "evaluation_sessions" ("id");

ALTER TABLE "evaluation_results" ADD FOREIGN KEY ("answer_document_id") REFERENCES "answer_documents" ("id");

ALTER TABLE "question_scores" ADD FOREIGN KEY ("evaluation_result_id") REFERENCES "evaluation_results" ("id");

ALTER TABLE "question_scores" ADD FOREIGN KEY ("sub_question_id") REFERENCES "sub_questions" ("id");

ALTER TABLE "evaluation_sessions" ADD FOREIGN KEY ("rubric_id") REFERENCES "rubrics" ("id");

ALTER TABLE "message_safety_reports" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id");

-- Indexes
CREATE INDEX ON "refresh_tokens" ("user_id");
CREATE INDEX ON "refresh_tokens" ("token_jti");
CREATE INDEX ON "password_reset_tokens" ("user_id");
CREATE INDEX ON "password_reset_tokens" ("token_jti");