version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.12.1
    ports: ["${QDRANT_PORT:-6333}:6333"]
    volumes:
      - qdrant_storage:/qdrant/storage
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  qdrant_storage:
  pg_data:
